on: [push]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Check out
      uses: actions/checkout@v4
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Build and Deploy Nikola
      uses: getnikola/nikola-action@v8
      with:
        dry_run: false
